# Generated by Django 2.1.5 on 2019-02-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='meal',
        ),
    ]
