# Generated by Django 2.1.5 on 2019-02-03 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190202_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$')])),
                ('person_count', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_request', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
