# Generated by Django 2.1.5 on 2019-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190203_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(null=True),
        ),
    ]
